name: QA-DEPLOY 

on:
  workflow_call:
    inputs:
      buildid_qaapiwfe:
       required: true
       description: 'DEV BUILD NUMBER TO DEPLOY. IF BLANK, DEPLOYS LATEST DEV BUILD.' 
       type: string
       
    secrets:
      JF_ARTIFACTORY_SECRET_1:
        required: true
      ACEONLINE_QA1_API_SERVER:
        required: true     
      ACEONLINE_QA1_WFE_SERVER:
        required: true
      ACEONLINE_QA2_API_SERVER:
        required: true     
      ACEONLINE_QA2_WFE_SERVER:
        required: true
      QA_API_PATH:
        required: true    
      QA_WFE_PATH:
        required: true      
      JF_UN:
        required: true
      JF_PW:
        required: true  
        
env:
 commitid: ${{ github.sha }}
 
jobs:
  QA-1:
    uses: AceHdw/cicd-common-wf/.github/workflows/QA1-CD.yml@main
    with:
      buildid_qaapiwfe: ${{ github.event.inputs.buildid_qaapiwfe }}    
      
    secrets:          
      JF_ARTIFACTORY_SECRET_1: "${{ secrets.JF_ARTIFACTORY_SECRET_1 }}" 
      JF_UN: "${{ secrets.JF_UN }}"
      JF_PW: "${{ secrets.JF_PW }}"      
      
      ACEONLINE_QA1_API_SERVER: "${{ secrets.ACEONLINE_QA1_API_SERVER }}"
      ACEONLINE_QA1_WFE_SERVER: "${{ secrets.ACEONLINE_QA1_WFE_SERVER }}"     
      
      ACEONLINE_QA2_API_SERVER: "${{ secrets.ACEONLINE_QA2_API_SERVER }}"
      ACEONLINE_QA2_WFE_SERVER: "${{ secrets.ACEONLINE_QA2_WFE_SERVER }}"     
      
      QA_API_PATH: "${{ secrets.QA_API_PATH }}"
      QA_WFE_PATH: "${{ secrets.QA_WFE_PATH }}"      

  QA-2:
    needs: QA-1
    uses: AceHdw/cicd-common-wf/.github/workflows/QA2-CD.yml@main
    with:
      buildid_qaapiwfe: ${{ github.event.inputs.buildid_qaapiwfe }}
      
    secrets:
      JF_ARTIFACTORY_SECRET_1: "${{ secrets.JF_ARTIFACTORY_SECRET_1 }}"
      JF_UN: "${{ secrets.JF_UN }}"
      JF_PW: "${{ secrets.JF_PW }}"
      
      ACEONLINE_QA1_API_SERVER: "${{ secrets.ACEONLINE_QA1_API_SERVER }}"
      ACEONLINE_QA1_WFE_SERVER: "${{ secrets.ACEONLINE_QA1_WFE_SERVER }}"      
      
      ACEONLINE_QA2_API_SERVER: "${{ secrets.ACEONLINE_QA2_API_SERVER }}"
      ACEONLINE_QA2_WFE_SERVER: "${{ secrets.ACEONLINE_QA2_WFE_SERVER }}"      
      
      QA_API_PATH: "${{ secrets.QA_API_PATH }}"
      QA_WFE_PATH: "${{ secrets.QA_WFE_PATH }}"
